# Generated by Django 5.1.4 on 2026-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_tag_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('contributor', 'Contributor'), ('author', 'Author'), ('editor', 'Editor'), ('admin', 'Admin')], default='subscriber', max_length=15),
        ),
    ]
